#cloud-config
users:
    - name: user1
      sudo: "ALL=(ALL) NOPASSWD:ALL"
      shell: /bin/bash
      ssh-authorized-keys:
          - "ssh-rsa key1"
salt_minion:
    pkg_name: 'salt-minion'
    config_dir: '/etc/salt'
    conf:
        file_client: local
    grains:
        yc:
            cloud-id:
                CLOUDID
            folder-id:
                FOLDERID
            token:
                TOKEN
        experiment:
            id:
                EXP_ID
        git:
            password:
                PASS
            user:
                USER
runcmd:
    - "sudo salt-call service.stop salt-minion"
    - "sudo salt-call service.disable salt-minion"
    - "sudo salt-call state.apply"
output:
    init:
        output: "> /var/log/cloud-init.out"
        error: "> /var/log/cloud-init.err"
    config:
        output: "> /var/log/cloud-config.out"
        error: "> /var/log/cloud-config.err"
    final:
        output: "> /var/log/cloud-final.out"
        error: "> /var/log/cloud-final.err"
